### PR TITLE
Exercise 7: Weather program with emojis

### PR DESCRIPTION
**Pull request by Cathe313**
Adding the emojis made the table behave weirdly, but everything else seems to work.

### CODE REVIEW

**Comment by ziad-saab** [comment]
@Cathe313 **Almost** 100%!!!! Can you find a way to NOT have a global `cityWeather` variable? Hint: you're only using it in one place ;)

**Comment by Cathe313** [comment]
Is it ok, though, to have a `.then` with nothing in it but a `console.log()`?

**Comment by Cathe313** [comment]
Ok, that works, although the code is a bit longer this way.

**Comment by ziad-saab** [comment]
@Cathe313 that is ok :) Sometimes we write code that's a little bit longer in order to make it a little bit more explicit what we are doing.

In this case, if you do a `return` and NOT a `console.log`, then it becomes a re-usable function that you can call from anywhere, and do a `console.log` whenever you feel like it.

**Pull request closed without merging**
