### PR TITLE
Exercise 5

### PR DESCRIPTION
**Pull request by karlysun**

### CODE REVIEW

**Comment by ziad-saab** [comment]
Normally you would use `map` to return a result that will compose the new array. Can you modify your code to have the `map` return something, and then use the returned promise to do your `console.log`

**Comment by karlysun** [comment]
The file was updated, please let me know if this is what you meant. Thanks

**Comment by ziad-saab** [comment]
Nope. Two things:
1. on line 23, you could return an object instead of an array. this would be much clearer
2. lines 30-46 should be done somewhere else, outside the `map`. `map`'s only purpose should be to take one element of the previous array, and `return` another element. By `return`, I mean that the last handler in the chain of promises of the mapping function should return something.

**Comment by karlysun** [comment]
I am unable to make my `.map` return something. Spent hours on this and it is not working. Will need some explainations.

**Comment by ziad-saab** [comment]
@karlysun check out this solution here and tell me what you think about it. If it's not clear I will explain it in class

https://github.com/noratop/promises-workshop/blob/447b5759d579f7f3024661c489b4a0564e68be07/exercise-5.js

**Comment by karlysun** [comment]
Oh, so you can use .map directly like a promise? Ok...

**Comment by ziad-saab** [comment]
yes :) it returns a "promise for an array"

--
Ziad Saab


*Full-Stack Web Developer*
www.ziad.cc


*Instructor / Head of Education*
www.decodemtl.com

**Comment by karlysun** [comment]
Ok well that was my problem, I didn't know that.

**Comment by ziad-saab** [comment]
My bad. I should've thought about it.

--
Ziad Saab


*Full-Stack Web Developer*
www.ziad.cc


*Instructor / Head of Education*
www.decodemtl.com

**Comment by karlysun** [comment]
No it's fine, I need to learn to read more carefully about stuff documentation. Now I know and I will not forget. I updated my file. Hope this is good now! Makes a lot of sense to use the .map like that!

**Comment by ziad-saab** [comment]
@karlysun Yes!! 100%!!! :)

**Pull request closed without merging**
